-- ============================================================
-- Lakara — Seed 3 Toko Demo (jalankan di phpMyAdmin)
-- Database: lakaraid_lakaracreative
-- Password semua akun demo: demo123456  |  Login: lakara.id/member
-- Foto produk: CDN DummyJSON (foto produk ASLI, reliable).
-- Bisa dijalankan berulang (hapus demo lama dulu).
-- ============================================================

ALTER TABLE stores ADD COLUMN IF NOT EXISTS product_image_ratio VARCHAR(10) DEFAULT '1:1';

DELETE FROM stores WHERE id IN ('demo_urban','demo_kopi','demo_rax');

-- ============================================================
-- TOKO 1 — Urban Threads (Streetwear) — PREMIUM — lakara.id/urbanthreads
-- ============================================================
INSERT INTO stores
(id, slug, name, tagline, description, logo, primary_color, active, member_active,
 member_email, member_password, instagram, tiktok, whatsapp, youtube,
 why_buy, products, links_bio, product_tier, tier_started_at, tier_expires_at)
VALUES (
 'demo_urban', 'urbanthreads', 'Urban Threads',
 'Streetwear lokal buat yang berani beda',
 'Brand streetwear asal Bandung. Produksi terbatas, bahan premium, desain ga pasaran.',
 'https://placehold.co/320x320/111111/ffffff?text=URBAN', '#111111', 1, 1,
 'urban@demo.lakara.id', SHA2(CONCAT('demo123456','lakara_salt'),256),
 'https://instagram.com/urbanthreads', 'https://tiktok.com/@urbanthreads', '6281234567801', 'https://youtube.com/@urbanthreads',
 '[{"title":"Bahan Premium","desc":"Cotton fleece 320gsm, adem dan awet dicuci berkali-kali."},{"title":"Limited Drop","desc":"Tiap desain cuma diproduksi sekali, ga bakal pasaran."},{"title":"Garansi Tukar","desc":"Salah ukuran? Tukar gratis dalam 7 hari."}]',
 '[
   {"id":"u1","slug":"hoodie-noir","name":"Hoodie Oversize Noir","tagline":"Hoodie hitam basic yang ga pernah salah","description":"Hoodie oversize bahan fleece tebal 320gsm. Jahitan rapi, kantong kanguru, hangat tapi ga gerah.","badge":"BESTSELLER","stock_label":"Stok tinggal 8","price":185000,"price_original":250000,"images":["https://cdn.dummyjson.com/product-images/mens-shirts/man-plaid-shirt/1.webp","https://cdn.dummyjson.com/product-images/mens-shirts/man-plaid-shirt/2.webp"],"marketplace":{"shopee":"https://shopee.co.id/urbanthreads","tokopedia":"https://tokopedia.com/urbanthreads","tiktok_shop":"https://tiktok.com/@urbanthreads/shop"},"marketplace_featured":["shopee","tokopedia"],"buy_link":"https://wa.me/6281234567801?text=Halo%20mau%20order%20Hoodie%20Noir","specs":[{"label":"Bahan","value":"Cotton Fleece 320gsm"},{"label":"Ukuran","value":"M, L, XL, XXL"},{"label":"Warna","value":"Hitam"}],"faq":[{"q":"Apakah unisex?","a":"Iya, fit oversize cocok cowok maupun cewek."},{"q":"Bisa COD?","a":"Bisa via marketplace pilihan kamu."}],"reviews":{"rating":4.9,"total":128,"items":[{"name":"Dimas","location":"Bandung","rating":5,"text":"Bahannya tebel enak, jahitan rapi. Worth it!"},{"name":"Sarah","location":"Jakarta","rating":5,"text":"Oversize-nya pas, warnanya ga luntur."}]},"published":true},
   {"id":"u2","slug":"boxy-tee","name":"Boxy Tee Heavyweight","tagline":"Kaos boxy 240gsm jatuh sempurna","description":"Kaos heavyweight potongan boxy. Cotton combed 24s tebal, ga nerawang, sablon plastisol awet.","badge":"NEW","stock_label":"Ready stock","price":95000,"price_original":130000,"images":["https://cdn.dummyjson.com/product-images/mens-shirts/gigabyte-aorus-men-tshirt/1.webp","https://cdn.dummyjson.com/product-images/mens-shirts/gigabyte-aorus-men-tshirt/2.webp"],"marketplace":{"shopee":"https://shopee.co.id/urbanthreads","tokopedia":"https://tokopedia.com/urbanthreads"},"marketplace_featured":["tokopedia","shopee"],"buy_link":"","specs":[{"label":"Bahan","value":"Cotton Combed 24s"},{"label":"Ukuran","value":"S, M, L, XL"}],"faq":[{"q":"Sablonnya gampang retak?","a":"Engga, pakai plastisol kualitas ekspor."}],"reviews":{"rating":4.8,"total":74,"items":[{"name":"Reza","location":"Surabaya","rating":5,"text":"Tebel banget, kaya kaos distro luar."}]},"published":true},
   {"id":"u3","slug":"trucker-cap","name":"Trucker Cap Classic","tagline":"Topi trucker dengan bordir timbul","description":"Trucker cap jaring belakang, adem dipakai. Bordir logo timbul, snapback adjustable.","badge":"","stock_label":"Pre-order 3 hari","price":75000,"price_original":0,"images":["https://cdn.dummyjson.com/product-images/mens-shirts/man-short-sleeve-shirt/1.webp"],"marketplace":{"shopee":"https://shopee.co.id/urbanthreads","lazada":"https://lazada.co.id/shop/urbanthreads"},"marketplace_featured":["shopee"],"buy_link":"https://wa.me/6281234567801?text=Order%20Trucker%20Cap","specs":[{"label":"Bahan","value":"Drill + Jaring"},{"label":"Ukuran","value":"All size adjustable"}],"faq":[],"reviews":{"rating":5,"total":31,"items":[{"name":"Aldi","location":"Bekasi","rating":5,"text":"Bordirnya rapi, bahan adem."}]},"published":true}
 ]',
 '{"title":"Urban Threads","bio":"Streetwear lokal buat yang berani beda. Limited drop tiap bulan.","bg_type":"gradient","bg_color":"#1a1a2e","gradient_from":"#ff3366","gradient_to":"#7c3aed","gradient_angle":135,"text_color":"#ffffff","accent_color":"#ffffff","title_color":"#ffffff","bio_color":"#ffe0ec","button_color":"#ffffff","button_text_color":"#1a1a2e","template":"gradient","card_style":"filled","card_radius":"full","hide_branding":true,"verified":true,"show_products":true,"button_animation":"pulse","links":[{"id":"l1","type":"instagram","label":"Instagram","url":"https://instagram.com/urbanthreads","image":"","enabled":true,"featured":true},{"id":"l2","type":"tiktok","label":"TikTok","url":"https://tiktok.com/@urbanthreads","image":"","enabled":true,"featured":false},{"id":"l3","type":"shopee","label":"Belanja di Shopee","url":"https://shopee.co.id/urbanthreads","image":"","enabled":true,"featured":false},{"id":"l4","type":"youtube_video","label":"Lookbook 2026","url":"https://youtube.com/watch?v=dQw4w9WgXcQ","image":"","enabled":true,"featured":false},{"id":"l5","type":"whatsapp","label":"Chat Admin","url":"https://wa.me/6281234567801","image":"","enabled":true,"featured":false}]}',
 'premium', NOW(), DATE_ADD(NOW(), INTERVAL 12 MONTH)
);

-- ============================================================
-- TOKO 2 — Kopi Senja (Coffee) — PRO — lakara.id/kopisenja
-- ============================================================
INSERT INTO stores
(id, slug, name, tagline, description, logo, primary_color, active, member_active,
 member_email, member_password, instagram, tiktok, whatsapp, youtube,
 why_buy, products, links_bio, product_tier, tier_started_at, tier_expires_at)
VALUES (
 'demo_kopi', 'kopisenja', 'Kopi Senja',
 'Kopi nusantara, diseduh dengan cinta',
 'Roastery kecil yang fokus ke single origin Indonesia. Fresh roast tiap minggu.',
 'https://placehold.co/320x320/8b5e3c/ffffff?text=KOPI', '#8B5E3C', 1, 1,
 'kopi@demo.lakara.id', SHA2(CONCAT('demo123456','lakara_salt'),256),
 'https://instagram.com/kopisenja', 'https://tiktok.com/@kopisenja', '6281234567802', '',
 '[{"title":"Fresh Roast","desc":"Disangrai tiap minggu, dikirim maksimal 3 hari setelah roasting."},{"title":"Single Origin","desc":"Biji pilihan dari Gayo, Toraja, dan Kintamani."},{"title":"Free Konsultasi","desc":"Bingung pilih biji? Chat kami, dibantu sampai cocok."}]',
 '[
   {"id":"k1","slug":"gayo-arabica-200g","name":"Gayo Arabica 200g","tagline":"Body tebal, aroma cokelat dan rempah","description":"Single origin Aceh Gayo. Profil medium roast, notes cokelat, kayu manis, sedikit citrus. Cocok buat tubruk maupun V60.","badge":"BESTSELLER","stock_label":"Fresh roast minggu ini","price":68000,"price_original":85000,"images":["https://cdn.dummyjson.com/product-images/mens-shirts/men-check-shirt/1.webp","https://cdn.dummyjson.com/product-images/mens-shirts/men-check-shirt/2.webp"],"marketplace":{"shopee":"https://shopee.co.id/kopisenja","tokopedia":"https://tokopedia.com/kopisenja"},"marketplace_featured":["shopee","tokopedia"],"buy_link":"https://wa.me/6281234567802?text=Order%20Gayo%20Arabica","specs":[{"label":"Berat","value":"200 gram"},{"label":"Roast","value":"Medium"},{"label":"Proses","value":"Honey"}],"faq":[{"q":"Bentuk biji atau bubuk?","a":"Bisa pilih biji utuh atau digiling sesuai alat seduh kamu."}],"reviews":{"rating":4.9,"total":210,"items":[{"name":"Bayu","location":"Yogyakarta","rating":5,"text":"Aromanya juara, body tebel pas buat tubruk."},{"name":"Nina","location":"Bandung","rating":5,"text":"Fresh banget, beda sama kopi supermarket."}]},"published":true},
   {"id":"k2","slug":"toraja-250g","name":"Toraja Sapan 250g","tagline":"Earthy, low acid, after taste manis","description":"Toraja Sapan dataran tinggi. Low acidity, body medium, notes herbal dan dark chocolate. Mantap buat espresso based.","badge":"","stock_label":"Ready stock","price":82000,"price_original":0,"images":["https://cdn.dummyjson.com/product-images/mens-shirts/man-short-sleeve-shirt/2.webp"],"marketplace":{"tokopedia":"https://tokopedia.com/kopisenja","tiktok_shop":"https://tiktok.com/@kopisenja/shop"},"marketplace_featured":["tokopedia"],"buy_link":"","specs":[{"label":"Berat","value":"250 gram"},{"label":"Roast","value":"Medium-Dark"}],"faq":[],"reviews":{"rating":4.8,"total":96,"items":[{"name":"Fajar","location":"Makassar","rating":5,"text":"Toraja asli, low acid enak buat lambung."}]},"published":true},
   {"id":"k3","slug":"tumbler-senja","name":"Tumbler Kopi Senja","tagline":"Tumbler stainless 500ml tahan panas 6 jam","description":"Tumbler eksklusif Kopi Senja. Stainless double wall, tahan panas 6 jam dingin 12 jam. Gratis stiker member.","badge":"MERCH","stock_label":"Limited","price":120000,"price_original":150000,"images":["https://cdn.dummyjson.com/product-images/mens-shirts/gigabyte-aorus-men-tshirt/3.webp"],"marketplace":{"shopee":"https://shopee.co.id/kopisenja"},"marketplace_featured":["shopee"],"buy_link":"https://wa.me/6281234567802?text=Order%20Tumbler","specs":[{"label":"Kapasitas","value":"500 ml"},{"label":"Bahan","value":"Stainless 304"}],"faq":[],"reviews":{"rating":5,"total":42,"items":[{"name":"Rara","location":"Semarang","rating":5,"text":"Awet panasnya beneran, desain cakep."}]},"published":true}
 ]',
 '{"title":"Kopi Senja","bio":"Roastery single origin Indonesia. Fresh roast tiap minggu, dikirim ke seluruh nusantara.","bg_type":"gradient","bg_color":"#3a2a1f","gradient_from":"#c79a6b","gradient_to":"#7b4f2c","gradient_angle":160,"text_color":"#ffffff","accent_color":"#ffe8d6","title_color":"#ffffff","bio_color":"#f3e3d3","button_color":"#ffffff","button_text_color":"#7b4f2c","template":"sunset","card_style":"filled","card_radius":"lg","hide_branding":false,"verified":false,"show_products":true,"button_animation":"none","links":[{"id":"l1","type":"instagram","label":"Instagram","url":"https://instagram.com/kopisenja","image":"","enabled":true,"featured":true},{"id":"l2","type":"whatsapp","label":"Order via WhatsApp","url":"https://wa.me/6281234567802","image":"","enabled":true,"featured":false},{"id":"l3","type":"shopee","label":"Shopee Official","url":"https://shopee.co.id/kopisenja","image":"","enabled":true,"featured":false},{"id":"l4","type":"tokopedia","label":"Tokopedia","url":"https://tokopedia.com/kopisenja","image":"","enabled":true,"featured":false}]}',
 'pro', NOW(), DATE_ADD(NOW(), INTERVAL 12 MONTH)
);

-- ============================================================
-- TOKO 3 — RAX Store (Gaming/Esports) — PREMIUM — lakara.id/raxstore
-- ============================================================
INSERT INTO stores
(id, slug, name, tagline, description, logo, primary_color, active, member_active,
 member_email, member_password, instagram, tiktok, whatsapp, youtube,
 why_buy, products, links_bio, product_tier, tier_started_at, tier_expires_at)
VALUES (
 'demo_rax', 'raxstore', 'RAX Store',
 'Gear and merch buat para gamers',
 'Toko gear gaming dan merchandise esports. Mousepad, jersey, keychain, semua original.',
 'https://placehold.co/320x320/7c3aed/ffffff?text=RAX', '#7c3aed', 1, 1,
 'rax@demo.lakara.id', SHA2(CONCAT('demo123456','lakara_salt'),256),
 'https://instagram.com/raxstore', 'https://tiktok.com/@raxstore', '6281234567803', 'https://youtube.com/@raxstore',
 '[{"title":"100% Original","desc":"Semua gear bergaransi resmi distributor."},{"title":"Pro Player Approved","desc":"Dipakai tim esports lokal di turnamen nasional."},{"title":"Kirim Cepat","desc":"Pesan sebelum jam 3 sore, hari itu juga dikirim."}]',
 '[
   {"id":"r1","slug":"mousepad-xl-rax","name":"Mousepad XL RAX Edition","tagline":"Speed surface 900x400mm anti slip","description":"Mousepad gaming ukuran XL. Permukaan micro-textured buat tracking presisi, base karet anti geser, pinggiran jahit rapi.","badge":"BESTSELLER","stock_label":"Stok tinggal 12","price":89000,"price_original":120000,"images":["https://cdn.dummyjson.com/product-images/mens-shoes/puma-future-rider-trainers/1.webp","https://cdn.dummyjson.com/product-images/mens-shoes/puma-future-rider-trainers/2.webp"],"marketplace":{"shopee":"https://shopee.co.id/raxstore","tokopedia":"https://tokopedia.com/raxstore","tiktok_shop":"https://tiktok.com/@raxstore/shop"},"marketplace_featured":["shopee","tiktok_shop"],"buy_link":"https://wa.me/6281234567803?text=Order%20Mousepad%20XL","specs":[{"label":"Ukuran","value":"900 x 400 x 4mm"},{"label":"Surface","value":"Speed"},{"label":"Base","value":"Anti-slip rubber"}],"faq":[{"q":"Bisa dicuci?","a":"Bisa, cukup lap basah atau cuci tangan dengan sabun lembut."}],"reviews":{"rating":4.9,"total":176,"items":[{"name":"Galih","location":"Depok","rating":5,"text":"Glide-nya enak buat valorant, lebar banget."},{"name":"Yoga","location":"Malang","rating":5,"text":"Jahitan pinggir rapi, ga gampang ngelupas."}]},"published":true},
   {"id":"r2","slug":"jersey-rax-2026","name":"Jersey RAX Esports 2026","tagline":"Jersey dryfit edisi tim 2026","description":"Jersey resmi tim RAX musim 2026. Bahan dryfit cepat kering, sablon sublim full print, ada nama di punggung opsional.","badge":"NEW","stock_label":"Pre-order","price":175000,"price_original":220000,"images":["https://cdn.dummyjson.com/product-images/mens-shoes/nike-air-jordan-1-red-and-black/1.webp","https://cdn.dummyjson.com/product-images/mens-shoes/nike-air-jordan-1-red-and-black/2.webp"],"marketplace":{"shopee":"https://shopee.co.id/raxstore","tokopedia":"https://tokopedia.com/raxstore"},"marketplace_featured":["tokopedia","shopee"],"buy_link":"","specs":[{"label":"Bahan","value":"Dryfit Sublim"},{"label":"Ukuran","value":"S sampai XXL"}],"faq":[{"q":"Bisa custom nama?","a":"Bisa, tulis nama dan nomor saat checkout."}],"reviews":{"rating":4.8,"total":88,"items":[{"name":"Bram","location":"Tangerang","rating":5,"text":"Bahan adem, sablon ga luntur. Keren!"}]},"published":true},
   {"id":"r3","slug":"keychain-tensura","name":"Keychain Akrilik Karakter","tagline":"Gantungan kunci akrilik 2 sisi","description":"Keychain akrilik dobel sisi, tebal 3mm, print tajam. Cocok buat tas, kunci, atau koleksi.","badge":"","stock_label":"Ready stock","price":30000,"price_original":45000,"images":["https://cdn.dummyjson.com/product-images/mens-shoes/sports-sneakers-off-white-red/1.webp"],"marketplace":{"shopee":"https://shopee.co.id/raxstore","tokopedia":"https://tokopedia.com/raxstore","lazada":"https://lazada.co.id/shop/raxstore","tiktok_shop":"https://tiktok.com/@raxstore/shop"},"marketplace_featured":["shopee","tokopedia"],"buy_link":"https://wa.me/6281234567803?text=Order%20Keychain","specs":[{"label":"Bahan","value":"Akrilik 3mm"},{"label":"Ukuran","value":"6 cm"}],"faq":[],"reviews":{"rating":5,"total":64,"items":[{"name":"Tio","location":"Solo","rating":5,"text":"Printnya tajam, tebel, murah lagi."}]},"published":true}
 ]',
 '{"title":"RAX Store","bio":"Gear gaming and merch esports original. Dipercaya pro player.","bg_type":"solid","bg_color":"#0d1117","gradient_from":"#7c3aed","gradient_to":"#00ffa3","gradient_angle":135,"text_color":"#e6edf3","accent_color":"#00ffa3","title_color":"#e6edf3","bio_color":"#8b949e","button_color":"#00ffa3","button_text_color":"#0d1117","template":"neon","card_style":"ghost","card_radius":"md","hide_branding":true,"verified":true,"show_products":true,"button_animation":"glow","links":[{"id":"l1","type":"youtube_video","label":"Highlight Grand Final","url":"https://youtube.com/watch?v=dQw4w9WgXcQ","image":"","enabled":true,"featured":false},{"id":"l2","type":"instagram","label":"Instagram","url":"https://instagram.com/raxstore","image":"","enabled":true,"featured":true},{"id":"l3","type":"tiktok","label":"TikTok","url":"https://tiktok.com/@raxstore","image":"","enabled":true,"featured":false},{"id":"l4","type":"shopee","label":"Shopee Store","url":"https://shopee.co.id/raxstore","image":"","enabled":true,"featured":false},{"id":"l5","type":"whatsapp","label":"Chat Admin","url":"https://wa.me/6281234567803","image":"","enabled":true,"featured":false}]}',
 'premium', NOW(), DATE_ADD(NOW(), INTERVAL 12 MONTH)
);

SELECT id, slug, name, product_tier FROM stores WHERE id IN ('demo_urban','demo_kopi','demo_rax');
